const BasicMenu = [
    {
        "id":1,
        "name":"首页",
        "path":"/basic/home"
    },
    {
        "id":2,
        "name":"UI",
        "path":"/basic/ui",
        "children":[
            {
                "id":3,
                "name":"按钮",
                "path":"/basic/ui/button"
            },
            {
                "id":4,
                "name":"弹框",
                "path":"/basic/ui/modals"
            },
            {
                "id":5,
                "name":"Loading",
                "path":"/basic/ui/loading"
            },
            {
                "id":6,
                "name":"通知提醒",
                "path":"/basic/ui/notification"
            },
            {
                "id":7,
                "name":"全局Message",
                "path":"/basic/ui/messages"
            },
            {
                "id":8,
                "name":"Tab页签",
                "path":"/basic/ui/tabs"
            },
            {
                "id":9,
                "name":"轮播图",
                "path":"/basic/ui/carousel"
            }
        ]
    },
    {
        "id":10,
        "name":"表单",
        "path":"/basic/form",
        "children":[
            {
                "id":11,
                "name":"登录",
                "path":"/basic/form/login"
            },
            {
                "id":12,
                "name":"注册",
                "path":"/basic/form/register"
            }
        ]
    },
    {
        "id":13,
        "name":"表格",
        "path":"/basic/tables",
        "children":[
            {
                "id":14,
                "name":"基础表格",
                "path":"/basic/table/low"
            },
            {
                "id":15,
                "name":"高级表格",
                "path":"/basic/table/high"
            }
        ]
    },
    {
        "id":16,
        "name":"富文本",
        "path":"/basic/rich"
    },
    {
        "id":17,
        "name":"画廊",
        "path":"/basic/gallery"
    },
    {
        "id":18,
        "name":"订单管理",
        "path":"/basic/order"
    },
    {
        "id":19,
        "name":"用户管理",
        "path":"/basic/user"
    },
    {
        "id":20,
        "name":"统计图",
        "path":"/basic/charts",
        "children":[
            {
                "id":21,
                "name":"柱形图",
                "path":"/basic/charts/bar",
            },
            {
                "id":22,
                "name":"饼图",
                "path":"/basic/charts/pie",
            },
            {
                "id":23,
                "name":"折线图",
                "path":"/basic/charts/line",
            }
        ]
    },
    {
        "id":24,
        "name":"权限管理",
        "path":"/basic/permission"
    }
]

export default BasicMenu